[package]
name = "nav_x"
version = "0.1.0"
authors = ["Jasper Meggitt <jasper.meggitt@gmail.com>"]

[dependencies]
wpilib = "0.2.2"
cargo-frc = "0.2.1"
libc = "0.2.43"

[package.metadata.frc]
team-number = 114
rio-address = "10.1.14.2"
target-dir = "./target"