version: 2
jobs:
  build:
    docker:
    - image: circleci/rust:1.31
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-{{ checksum "Cargo.toml" }}-{{ .Branch }}-{{ .Revision }}
          - v1-{{ checksum "Cargo.toml" }}-{{ .Branch }}-
          - v1-{{ checksum "Cargo.toml" }}-
          - v1-
    - run:
        command: cargo build
    - save_cache:
        key: v1-{{ checksum "Cargo.toml" }}-{{ .Branch }}-{{ .Revision }}
        paths:
        - target
workflows:
  version: 2
  workflow:
    jobs:
    - build
